#!/bin/bash

# =============================================================================
# ECTROPY BRANCH ANALYSIS & MANAGEMENT SCRIPT
# =============================================================================
# 
# PURPOSE: Analyze all branches and provide merge recommendations
# USAGE: ./analyze-branches.sh [--merge] [--cleanup]
# 
# This script will:
# 1. Analyze all local and remote branches
# 2. Identify merge conflicts and divergence
# 3. Generate safe merge strategies
# 4. Recommend branch cleanup actions
# 
# =============================================================================

set -e

# Configuration
MERGE_MODE=false
CLEANUP_MODE=false
OUTPUT_DIR="branch-analysis"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --merge)
      MERGE_MODE=true
      shift
      ;;
    --cleanup)
      CLEANUP_MODE=true
      shift
      ;;
    *)
      echo "Unknown option: $1"
      echo "Usage: $0 [--merge] [--cleanup]"
      exit 1
      ;;
  esac
done

# Create output directory
mkdir -p "$OUTPUT_DIR"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}🌿 ECTROPY BRANCH ANALYSIS REPORT${NC}"
echo -e "${BLUE}==================================${NC}"
echo "Date: $(date)"
echo "Current branch: $(git branch --show-current)"
echo ""

# Initialize report files
REPORT_FILE="$OUTPUT_DIR/branch-analysis-$TIMESTAMP.md"
MERGE_SCRIPT="$OUTPUT_DIR/safe-merge-$TIMESTAMP.sh"
CLEANUP_SCRIPT="$OUTPUT_DIR/branch-cleanup-$TIMESTAMP.sh"

cat > "$REPORT_FILE" << EOF
# 🌿 ECTROPY BRANCH ANALYSIS REPORT
Date: $(date)
Current branch: $(git branch --show-current)

## 📊 BRANCH INVENTORY

EOF

cat > "$MERGE_SCRIPT" << 'EOF'
#!/bin/bash
# Safe merge commands generated by branch analysis
# Review and execute manually!

set -e

echo "🔄 Executing safe merge operations..."

# Create backup before merging
BACKUP_BRANCH="backup/pre-merge-$(date +%Y%m%d-%H%M%S)"
echo "📋 Creating backup branch: $BACKUP_BRANCH"
git checkout -b "$BACKUP_BRANCH"
git checkout main

EOF

cat > "$CLEANUP_SCRIPT" << 'EOF'
#!/bin/bash
# Branch cleanup commands generated by analysis
# Review carefully before executing!

set -e

echo "🧹 Executing branch cleanup operations..."

EOF

chmod +x "$MERGE_SCRIPT"
chmod +x "$CLEANUP_SCRIPT"

# 1. LIST ALL BRANCHES
echo -e "${GREEN}## 📋 All Branches${NC}"
echo "### All Branches" >> "$REPORT_FILE"

# Local branches
echo "#### Local Branches" >> "$REPORT_FILE"
git branch --format='- %(refname:short) | %(committerdate:short) | %(authorname) | %(subject)' >> "$REPORT_FILE"

# Remote branches
echo "" >> "$REPORT_FILE"
echo "#### Remote Branches" >> "$REPORT_FILE"
git branch -r --format='- %(refname:short) | %(committerdate:short) | %(authorname) | %(subject)' >> "$REPORT_FILE"

# 2. BRANCH ACTIVITY ANALYSIS
echo -e "${YELLOW}## 📊 Branch Activity Analysis${NC}"
echo "" >> "$REPORT_FILE"
echo "## 📊 BRANCH ACTIVITY ANALYSIS" >> "$REPORT_FILE"

# Active branches (commits in last 30 days)
echo "### Active Branches (Last 30 Days)" >> "$REPORT_FILE"
ACTIVE_COUNT=0
git for-each-ref --format='%(refname:short) %(committerdate)' refs/heads/ refs/remotes/ | \
  while read branch date; do
    if [[ $(date -d "$date" +%s 2>/dev/null || echo "0") -gt $(date -d "30 days ago" +%s) ]]; then
      echo "- $branch ($date)" >> "$REPORT_FILE"
      ((ACTIVE_COUNT++))
    fi
  done

# Stale branches (no commits in 60+ days)
echo "" >> "$REPORT_FILE"
echo "### Stale Branches (60+ Days)" >> "$REPORT_FILE"
STALE_COUNT=0
git for-each-ref --format='%(refname:short) %(committerdate)' refs/heads/ | \
  while read branch date; do
    if [[ $(date -d "$date" +%s 2>/dev/null || echo "0") -lt $(date -d "60 days ago" +%s) ]]; then
      if [ "$branch" != "main" ] && [ "$branch" != "master" ]; then
        echo "- $branch ($date)" >> "$REPORT_FILE"
        echo "git branch -D $branch  # CAUTION: Review before deleting" >> "$CLEANUP_SCRIPT"
        ((STALE_COUNT++))
      fi
    fi
  done

# 3. MERGE ANALYSIS
echo -e "${BLUE}## 🔄 Merge Analysis${NC}"
echo "" >> "$REPORT_FILE"
echo "## 🔄 MERGE ANALYSIS" >> "$REPORT_FILE"

CURRENT_BRANCH=$(git branch --show-current)

# Priority branches for merging
PRIORITY_BRANCHES=(
  "develop"
  "development"
  "production"
  "feature/typescript-fixes"
  "feature/dao-governance"
  "feature/speckle-integration"
  "feature/bim-integration"
  "hotfix/express-types"
)

echo "### Priority Branches Analysis" >> "$REPORT_FILE"

for branch in "${PRIORITY_BRANCHES[@]}"; do
  if git show-ref --verify --quiet "refs/heads/$branch" 2>/dev/null || \
     git show-ref --verify --quiet "refs/remotes/origin/$branch" 2>/dev/null; then
    
    echo "#### Branch: $branch" >> "$REPORT_FILE"
    
    # Check if branch exists locally or remotely
    if git show-ref --verify --quiet "refs/heads/$branch" 2>/dev/null; then
      BRANCH_REF="$branch"
    else
      BRANCH_REF="origin/$branch"
    fi
    
    # Check merge status
    if git merge-base --is-ancestor "$BRANCH_REF" HEAD 2>/dev/null; then
      echo "- ✅ Already merged or behind main" >> "$REPORT_FILE"
      if [ "$branch" != "$CURRENT_BRANCH" ]; then
        echo "git branch -d $branch  # Safe to delete - already merged" >> "$CLEANUP_SCRIPT"
      fi
    elif git merge-base --is-ancestor HEAD "$BRANCH_REF" 2>/dev/null; then
      echo "- ⚡ Can be fast-forwarded" >> "$REPORT_FILE"
      echo "git merge $BRANCH_REF --ff-only" >> "$MERGE_SCRIPT"
    else
      echo "- 🔄 Requires three-way merge" >> "$REPORT_FILE"
      
      # Check for potential conflicts
      MERGE_BASE=$(git merge-base HEAD "$BRANCH_REF" 2>/dev/null || echo "")
      if [ -n "$MERGE_BASE" ]; then
        CONFLICT_FILES=$(git merge-tree "$MERGE_BASE" HEAD "$BRANCH_REF" 2>/dev/null | grep -c "<<<<<<< " || echo "0")
        if [ "$CONFLICT_FILES" -gt 0 ]; then
          echo "- ⚠️  $CONFLICT_FILES potential conflict(s) detected" >> "$REPORT_FILE"
          echo "# MANUAL REVIEW REQUIRED: $branch has potential conflicts" >> "$MERGE_SCRIPT"
        else
          echo "- ✅ No conflicts detected" >> "$REPORT_FILE"
          echo "git merge $BRANCH_REF --no-ff -m \"Merge branch '$branch' into main\"" >> "$MERGE_SCRIPT"
        fi
      fi
      
      # Show divergence
      AHEAD=$(git rev-list --count HEAD.."$BRANCH_REF" 2>/dev/null || echo "0")
      BEHIND=$(git rev-list --count "$BRANCH_REF"..HEAD 2>/dev/null || echo "0")
      echo "- 📊 Divergence: $AHEAD commits ahead, $BEHIND commits behind" >> "$REPORT_FILE"
    fi
    
    # Show last commit info
    LAST_COMMIT=$(git log -1 --format='%h - %s (%an, %ar)' "$BRANCH_REF" 2>/dev/null || echo "Unable to retrieve")
    echo "- 📝 Last commit: $LAST_COMMIT" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
  else
    echo "#### Branch: $branch" >> "$REPORT_FILE"
    echo "- ❌ Branch not found" >> "$REPORT_FILE"
    echo "" >> "$REPORT_FILE"
  fi
done

# 4. CLEANUP RECOMMENDATIONS
echo -e "${RED}## 🧹 Cleanup Recommendations${NC}"
echo "" >> "$REPORT_FILE"
echo "## 🧹 CLEANUP RECOMMENDATIONS" >> "$REPORT_FILE"

# Merged branches
echo "### Branches Fully Merged into Main" >> "$REPORT_FILE"
git branch --merged main | grep -v "main\|master" | while read branch; do
  echo "- $branch" >> "$REPORT_FILE"
  echo "git branch -d $branch" >> "$CLEANUP_SCRIPT"
done

# Remote tracking cleanup
echo "" >> "$REPORT_FILE"
echo "### Remote Tracking Cleanup" >> "$REPORT_FILE"
echo "- Run: git remote prune origin" >> "$REPORT_FILE"
echo "git remote prune origin" >> "$CLEANUP_SCRIPT"

# 5. BRANCH NAMING STANDARDS CHECK
echo "" >> "$REPORT_FILE"
echo "## 📝 BRANCH NAMING STANDARDS" >> "$REPORT_FILE"

echo "### Branches Following Standards" >> "$REPORT_FILE"
git branch --format='%(refname:short)' | while read branch; do
  if [[ "$branch" =~ ^(feature|bugfix|hotfix|release)/.+ ]]; then
    echo "- ✅ $branch" >> "$REPORT_FILE"
  elif [[ "$branch" =~ ^(main|master|develop|development|production)$ ]]; then
    echo "- ✅ $branch (core branch)" >> "$REPORT_FILE"
  else
    echo "- ⚠️  $branch (non-standard naming)" >> "$REPORT_FILE"
  fi
done

# 6. GENERATE MERGE STRATEGY
echo "" >> "$MERGE_SCRIPT" << 'EOF'

# Post-merge validation
echo "🧪 Running post-merge validation..."

# Build test
if command -v npm > /dev/null; then
  echo "Running build test..."
  npm run build || echo "⚠️  Build failed after merge"
fi

# Type check
if command -v npx > /dev/null; then
  echo "Running type check..."
  npx tsc --noEmit || echo "⚠️  Type check failed after merge"
fi

echo "✅ Merge operations completed"
echo "📋 Next steps:"
echo "1. Review merge results"
echo "2. Run full test suite"
echo "3. Update documentation if needed"
EOF

# 7. FINAL SUMMARY
TOTAL_BRANCHES=$(git branch -a | wc -l)
LOCAL_BRANCHES=$(git branch | wc -l)
REMOTE_BRANCHES=$(git branch -r | wc -l)

cat >> "$REPORT_FILE" << EOF

## 📊 FINAL STATISTICS
- Total branches: $TOTAL_BRANCHES
- Local branches: $LOCAL_BRANCHES
- Remote branches: $REMOTE_BRANCHES
- Current branch: $CURRENT_BRANCH

## 📋 RECOMMENDED ACTIONS

### Immediate Actions
1. Review this report: $REPORT_FILE
2. Execute safe merges: $MERGE_SCRIPT
3. Clean up stale branches: $CLEANUP_SCRIPT

### Manual Review Required
- Branches with potential conflicts
- Non-standard branch names
- Unmerged feature branches older than 60 days

### Best Practices Going Forward
- Use standard branch naming: feature/description, bugfix/issue, hotfix/critical
- Regular branch cleanup (weekly)
- Merge feature branches promptly after completion
- Keep main branch stable and up-to-date

EOF

# Execute actions if requested
if [ "$MERGE_MODE" = true ]; then
  echo -e "${GREEN}🔄 Executing merge operations...${NC}"
  echo "Review the merge script before proceeding:"
  echo "cat $MERGE_SCRIPT"
  echo ""
  echo "Execute with: bash $MERGE_SCRIPT"
fi

if [ "$CLEANUP_MODE" = true ]; then
  echo -e "${YELLOW}🧹 Cleanup script generated...${NC}"
  echo "Review the cleanup script before proceeding:"
  echo "cat $CLEANUP_SCRIPT"
  echo ""
  echo "Execute with: bash $CLEANUP_SCRIPT"
fi

echo ""
echo -e "${GREEN}📋 Branch analysis complete!${NC}"
echo "Results saved to:"
echo "  - Analysis report: $REPORT_FILE"
echo "  - Merge script: $MERGE_SCRIPT"
echo "  - Cleanup script: $CLEANUP_SCRIPT"
echo ""
echo "Next steps:"
echo "1. Review the analysis report"
echo "2. Execute merge script for priority branches"
echo "3. Clean up stale branches after review"
echo "4. Establish branch naming standards"
