#!/bin/bash

# =============================================================================
# ECTROPY CRITICAL FILES AUDIT & CLEANUP SCRIPT
# =============================================================================
# 
# PURPOSE: Systematically identify and categorize files for cleanup/documentation
# USAGE: ./critical-files-audit.sh [--cleanup] [--dry-run]
# 
# This script will:
# 1. Categorize all files by importance and usage
# 2. Identify files safe for removal
# 3. Flag files needing documentation
# 4. Generate cleanup recommendations
# 
# =============================================================================

set -e

# Configuration
CLEANUP_MODE=false
DRY_RUN=false
OUTPUT_DIR="audit-results"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --cleanup)
      CLEANUP_MODE=true
      shift
      ;;
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    *)
      echo "Unknown option: $1"
      echo "Usage: $0 [--cleanup] [--dry-run]"
      exit 1
      ;;
  esac
done

# Create output directory
mkdir -p "$OUTPUT_DIR"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}🔍 ECTROPY FILES AUDIT REPORT${NC}"
echo -e "${BLUE}=============================${NC}"
echo "Date: $(date)"
echo "Mode: $([ "$CLEANUP_MODE" = true ] && echo "CLEANUP" || echo "AUDIT ONLY")"
echo "Dry Run: $DRY_RUN"
echo ""

# Initialize report files
SUMMARY_FILE="$OUTPUT_DIR/audit-summary-$TIMESTAMP.md"
SAFE_CLEANUP_FILE="$OUTPUT_DIR/safe-cleanup-$TIMESTAMP.sh"
REVIEW_NEEDED_FILE="$OUTPUT_DIR/review-needed-$TIMESTAMP.md"

cat > "$SUMMARY_FILE" << EOF
# 🔍 ECTROPY FILES AUDIT REPORT
Date: $(date)
Mode: $([ "$CLEANUP_MODE" = true ] && echo "CLEANUP" || echo "AUDIT ONLY")

## 📊 SUMMARY STATISTICS

EOF

cat > "$SAFE_CLEANUP_FILE" << 'EOF'
#!/bin/bash
# Safe cleanup commands generated by audit
# Review before executing!

set -e

echo "🧹 Executing safe cleanup operations..."

EOF

chmod +x "$SAFE_CLEANUP_FILE"

# 1. FIND SAFE-TO-REMOVE FILES
echo -e "${GREEN}## 🗑️ SAFE TO REMOVE FILES${NC}"
echo "## 🗑️ SAFE TO REMOVE FILES" >> "$SUMMARY_FILE"

# Temporary files
echo "### Temporary Files" >> "$SUMMARY_FILE"
find . -name "*.tmp" -o -name "*.temp" -o -name "*.cache" \
  -not -path "*/node_modules/*" -not -path "*/.*" > "$OUTPUT_DIR/temp-files.txt"

TEMP_COUNT=$(wc -l < "$OUTPUT_DIR/temp-files.txt")
echo "Found $TEMP_COUNT temporary files" | tee -a "$SUMMARY_FILE"

if [ $TEMP_COUNT -gt 0 ]; then
  echo "echo 'Removing temporary files...'" >> "$SAFE_CLEANUP_FILE"
  while read -r file; do
    echo "rm -f \"$file\"" >> "$SAFE_CLEANUP_FILE"
  done < "$OUTPUT_DIR/temp-files.txt"
fi

# Backup files
echo "### Backup Files" >> "$SUMMARY_FILE"
find . -name "*.backup" -o -name "*.old" -o -name "*.bak" \
  -not -path "*/node_modules/*" -not -path "*/backups/*" > "$OUTPUT_DIR/backup-files.txt"

BACKUP_COUNT=$(wc -l < "$OUTPUT_DIR/backup-files.txt")
echo "Found $BACKUP_COUNT backup files" | tee -a "$SUMMARY_FILE"

if [ $BACKUP_COUNT -gt 0 ]; then
  echo "echo 'Removing backup files...'" >> "$SAFE_CLEANUP_FILE"
  while read -r file; do
    echo "rm -f \"$file\"" >> "$SAFE_CLEANUP_FILE"
  done < "$OUTPUT_DIR/backup-files.txt"
fi

# Log files
echo "### Log Files" >> "$SUMMARY_FILE"
find . -name "*.log" -o -name "debug*.txt" -o -name "error*.txt" \
  -not -path "*/node_modules/*" -not -path "*/logs/*" > "$OUTPUT_DIR/log-files.txt"

LOG_COUNT=$(wc -l < "$OUTPUT_DIR/log-files.txt")
echo "Found $LOG_COUNT log files" | tee -a "$SUMMARY_FILE"

# 2. FIND FILES NEEDING DOCUMENTATION
echo -e "${YELLOW}## 📚 FILES NEEDING DOCUMENTATION${NC}"
echo "" >> "$SUMMARY_FILE"
echo "## 📚 FILES NEEDING DOCUMENTATION" >> "$SUMMARY_FILE"

# Key files without proper headers
echo "### Key Files Missing Documentation Headers" >> "$SUMMARY_FILE"
find . -name "*.ts" -o -name "*.tsx" -o -name "*.js" -o -name "*.jsx" | \
  grep -v node_modules | grep -v dist | grep -v build | \
  while read -r file; do
    if ! head -10 "$file" | grep -q "PURPOSE:\|DESCRIPTION:\|\*\*\*"; then
      echo "- $file" >> "$SUMMARY_FILE"
    fi
  done

# Large files that should be documented
echo "### Large Files (>200 lines) Needing Documentation" >> "$SUMMARY_FILE"
find . -name "*.ts" -o -name "*.tsx" -o -name "*.js" -o -name "*.jsx" | \
  grep -v node_modules | grep -v dist | grep -v build | \
  while read -r file; do
    lines=$(wc -l < "$file" 2>/dev/null || echo "0")
    if [ "$lines" -gt 200 ]; then
      if ! head -20 "$file" | grep -q "PURPOSE:\|DESCRIPTION:\|\*\*\*"; then
        echo "- $file ($lines lines)" >> "$SUMMARY_FILE"
      fi
    fi
  done

# 3. FIND DISABLED/LEGACY CODE
echo -e "${RED}## 💤 DISABLED/LEGACY CODE${NC}"
echo "" >> "$SUMMARY_FILE"
echo "## 💤 DISABLED/LEGACY CODE" >> "$SUMMARY_FILE"

# Disabled directories
echo "### Disabled Directories" >> "$SUMMARY_FILE"
find . -type d -name "*disabled*" -o -name "*legacy*" -o -name "*deprecated*" | \
  grep -v node_modules >> "$SUMMARY_FILE" || echo "None found" >> "$SUMMARY_FILE"

# Files with TODO/FIXME
echo "### Files with TODO/FIXME Comments" >> "$SUMMARY_FILE"
grep -r "TODO\|FIXME\|HACK\|XXX" . \
  --include="*.ts" --include="*.tsx" --include="*.js" --include="*.jsx" \
  --exclude-dir=node_modules --exclude-dir=dist --exclude-dir=build | \
  head -20 >> "$SUMMARY_FILE" || echo "None found" >> "$SUMMARY_FILE"

# 4. DUPLICATE FUNCTIONALITY ANALYSIS
echo -e "${BLUE}## 🔄 POTENTIAL DUPLICATES${NC}"
echo "" >> "$SUMMARY_FILE"
echo "## 🔄 POTENTIAL DUPLICATES" >> "$SUMMARY_FILE"

# Multiple auth services
echo "### Authentication Services" >> "$SUMMARY_FILE"
find . -name "*auth*" -type f \( -name "*.ts" -o -name "*.js" \) | \
  grep -v node_modules | grep -v test >> "$SUMMARY_FILE" || echo "None found" >> "$SUMMARY_FILE"

# Multiple database clients
echo "### Database Clients" >> "$SUMMARY_FILE"
find . -name "*database*" -o -name "*client*" -o -name "*connection*" | \
  grep -v node_modules | grep -v test >> "$SUMMARY_FILE" || echo "None found" >> "$SUMMARY_FILE"

# 5. SECURITY ANALYSIS
echo -e "${RED}## 🔒 SECURITY REVIEW NEEDED${NC}"
echo "" >> "$SUMMARY_FILE"
echo "## 🔒 SECURITY REVIEW NEEDED" >> "$SUMMARY_FILE"

# Files with sensitive keywords
echo "### Files with Potential Security Issues" >> "$SUMMARY_FILE"
grep -r "password\|secret\|key\|token" . \
  --include="*.ts" --include="*.tsx" --include="*.js" --include="*.jsx" \
  --exclude-dir=node_modules --exclude-dir=dist | \
  grep -v "\.env\." | head -10 >> "$SUMMARY_FILE" || echo "None found" >> "$SUMMARY_FILE"

# Hardcoded credentials (basic check)
echo "### Potential Hardcoded Credentials" >> "$SUMMARY_FILE"
grep -r "password\s*=\s*['\"]" . \
  --include="*.ts" --include="*.js" \
  --exclude-dir=node_modules | head -5 >> "$SUMMARY_FILE" || echo "None found" >> "$SUMMARY_FILE"

# 6. PERFORMANCE ANALYSIS
echo -e "${YELLOW}## ⚡ PERFORMANCE REVIEW${NC}"
echo "" >> "$SUMMARY_FILE"
echo "## ⚡ PERFORMANCE REVIEW" >> "$SUMMARY_FILE"

# Large files
echo "### Large Files (>1000 lines)" >> "$SUMMARY_FILE"
find . -name "*.ts" -o -name "*.tsx" -o -name "*.js" -o -name "*.jsx" | \
  grep -v node_modules | grep -v dist | grep -v build | \
  xargs wc -l 2>/dev/null | sort -nr | head -10 | \
  awk '$1 > 1000 {print "- " $2 " (" $1 " lines)"}' >> "$SUMMARY_FILE"

# Nested callbacks (potential callback hell)
echo "### Files with Deep Nesting (Potential Refactoring)" >> "$SUMMARY_FILE"
find . -name "*.ts" -o -name "*.js" | \
  grep -v node_modules | \
  xargs grep -l "function.*function.*function" | head -5 >> "$SUMMARY_FILE" || echo "None found" >> "$SUMMARY_FILE"

# 7. GENERATE FINAL SUMMARY
TOTAL_FILES=$(find . -type f -not -path "*/node_modules/*" -not -path "*/.*" | wc -l)
TS_FILES=$(find . -name "*.ts" -o -name "*.tsx" | grep -v node_modules | wc -l)
JS_FILES=$(find . -name "*.js" -o -name "*.jsx" | grep -v node_modules | wc -l)

cat >> "$SUMMARY_FILE" << EOF

## 📊 FINAL STATISTICS
- Total files: $TOTAL_FILES
- TypeScript files: $TS_FILES
- JavaScript files: $JS_FILES
- Temporary files: $TEMP_COUNT
- Backup files: $BACKUP_COUNT
- Log files: $LOG_COUNT

## 📋 RECOMMENDED ACTIONS

### Immediate (Safe to Execute)
1. Run the generated cleanup script: ./$SAFE_CLEANUP_FILE
2. Remove confirmed disabled directories
3. Clear TODO/FIXME items or document them

### Requires Review
1. Evaluate duplicate authentication services
2. Consolidate database connection logic
3. Review large files for potential splitting
4. Document key modules missing headers

### Security Priority
1. Review files with sensitive keywords
2. Ensure no hardcoded credentials
3. Validate environment variable usage

EOF

# Execute cleanup if requested
if [ "$CLEANUP_MODE" = true ]; then
  echo -e "${GREEN}🧹 Executing safe cleanup operations...${NC}"
  if [ "$DRY_RUN" = true ]; then
    echo "DRY RUN: Would execute cleanup script"
    cat "$SAFE_CLEANUP_FILE"
  else
    bash "$SAFE_CLEANUP_FILE"
    echo "✅ Safe cleanup completed"
  fi
fi

echo ""
echo -e "${GREEN}📋 Audit complete!${NC}"
echo "Results saved to:"
echo "  - Summary: $SUMMARY_FILE"
echo "  - Cleanup script: $SAFE_CLEANUP_FILE"
echo ""
echo "Next steps:"
echo "1. Review the summary report"
echo "2. Execute safe cleanup: bash $SAFE_CLEANUP_FILE"
echo "3. Address items requiring manual review"
echo "4. Run documentation improvements"
