/**
 * Generate API Documentation Markdown from JSON
 * Enterprise JSON-first pattern implementation
 */

import { promises as fs } from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import { dirname } from 'path';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

interface APISpec {
  documentId: string;
  version: string;
  lastUpdated: string;
  metadata: {
    title: string;
    description: string;
    humanViewUrl: string;
  };
  architecture: any;
  baseUrls: any;
  endpoints: any;
  authentication: any;
  [key: string]: any;
}

async function generateAPIDocs() {
  const jsonPath = path.resolve(__dirname, '../../apps/mcp-server/data/api-specification.json');
  const mdPath = path.resolve(__dirname, '../../docs/API_SPECIFICATION.md');

  console.log(`📖 Generating API documentation...`);
  console.log(`   Source: ${jsonPath}`);
  console.log(`   Output: ${mdPath}`);

  // Read JSON spec
  const spec: APISpec = JSON.parse(await fs.readFile(jsonPath, 'utf-8'));

  // Generate markdown with auto-gen header
  const markdown = generateMarkdown(spec, jsonPath);

  // Write to file
  await fs.writeFile(mdPath, markdown, 'utf-8');

  console.log(`✅ Generated ${mdPath}`);
}

function generateMarkdown(spec: APISpec, sourcePath: string): string {
  const now = new Date().toISOString();
  const relativeSource = sourcePath.replace(/\\/g, '/').split('/').slice(-4).join('/');

  return `# ${spec.metadata.title}

**Generated:** ${now}
**Source:** \`${relativeSource}\` (automated - DO NOT EDIT THIS FILE DIRECTLY)
**Version:** ${spec.version}
**Last Updated:** ${spec.lastUpdated}

---

⚠️ **IMPORTANT: This file is auto-generated**

This markdown file is automatically generated from \`${relativeSource}\`.

**To make changes:**
1. Edit \`${relativeSource}\` directly
2. Validate: \`pnpm docs:validate\`
3. Regenerate markdown: \`pnpm docs:generate\` or \`pnpm tsx scripts/docs/generate-api-docs.ts\`
4. Commit both JSON and markdown files

**Never edit this file directly** - your changes will be overwritten on the next generation.

---

## Overview

${spec.metadata.description}

**Environment:** ${spec.metadata.tags?.join(', ') || 'Production'}

---

## Architecture

### ${spec.architecture.design === 'dual-server' ? 'Dual-Server Design' : 'Architecture'}

${generateArchitectureSection(spec.architecture)}

### Operating Modes

${generateOperatingModes(spec.operatingModes)}

---

## Authentication

${generateAuthenticationSection(spec.authentication)}

---

## Base URLs

${generateBaseURLs(spec.baseUrls)}

---

## Endpoints

${generateEndpointsSection(spec.endpoints)}

---

## Error Handling

${generateErrorHandling(spec.errorHandling)}

---

## Rate Limiting

${generateRateLimiting(spec.rateLimiting)}

---

## Security

${generateSecuritySection(spec.security)}

---

## Environment Configuration

### Required Variables

${generateEnvironmentVariables(spec.environmentConfiguration.required)}

### Optional Variables

${generateEnvironmentVariables(spec.environmentConfiguration.optional)}

---

## Related Documents

${generateRelatedDocs(spec.relatedDocuments)}

---

**Generated by:** \`scripts/docs/generate-api-docs.ts\`
**Documentation Standard:** Enterprise JSON-First Pattern
**Schema Version:** ${spec.version}
`;
}

function generateArchitectureSection(arch: any): string {
  let md = '';

  if (arch.servers) {
    md += '**Servers:**\n\n';
    for (const [name, server] of Object.entries(arch.servers)) {
      const s = server as any;
      md += `- **${name.toUpperCase()} Server** (Port ${s.port})\n`;
      md += `  - Protocol: ${s.protocol}\n`;
      md += `  - Description: ${s.description}\n`;
      md += `  - Capabilities: ${s.capabilities.join(', ')}\n\n`;
    }
  }

  if (arch.healthAggregator) {
    md += '**Health Aggregator:**\n';
    md += `- Dependencies: ${arch.healthAggregator.dependencies.join(', ')}\n`;
    md += `- ${arch.healthAggregator.description}\n\n`;
  }

  return md;
}

function generateOperatingModes(modes: any): string {
  let md = '';

  for (const [name, mode] of Object.entries(modes)) {
    const m = mode as any;
    md += `**${name.toUpperCase()}${m.default ? ' (Default)' : ''}:**\n`;
    md += `- ${m.description}\n`;
    md += `- Servers: ${m.servers.join(', ')}\n`;
    md += `- Database: ${m.database ? 'Yes' : 'No'}\n`;
    md += `- Monitoring: ${m.monitoring ? 'Yes' : 'No'}\n`;
    if (m.environmentVariable) {
      md += `- Environment: \`${m.environmentVariable}\`\n`;
    }
    md += '\n';
  }

  return md;
}

function generateAuthenticationSection(auth: any): string {
  let md = '**Methods:**\n\n';

  for (const [name, method] of Object.entries(auth.methods)) {
    const m = method as any;
    md += `### ${name.toUpperCase()}\n\n`;
    if (m.header) md += `- Header: \`${m.header}\`\n`;
    if (m.environmentVariable) md += `- Environment Variable: \`${m.environmentVariable}\`\n`;
    if (m.algorithm) md += `- Algorithm: ${m.algorithm}\n`;
    if (m.providers) md += `- Providers: ${m.providers.join(', ')}\n`;
    md += `- Description: ${m.description}\n`;
    md += `- Applies To: ${Array.isArray(m.appliesTo) ? m.appliesTo.join(', ') : m.appliesTo}\n\n`;
  }

  if (auth.publicEndpoints) {
    md += '**Public Endpoints (No Authentication):**\n\n';
    auth.publicEndpoints.forEach((endpoint: string) => {
      md += `- \`${endpoint}\`\n`;
    });
    md += '\n';
  }

  return md;
}

function generateBaseURLs(urls: any): string {
  let md = '';
  for (const [name, url] of Object.entries(urls)) {
    md += `- **${name}**: \`${url}\`\n`;
  }
  return md + '\n';
}

function generateEndpointsSection(endpoints: any): string {
  let md = '';

  for (const [category, categoryEndpoints] of Object.entries(endpoints)) {
    md += `### ${category.charAt(0).toUpperCase() + category.slice(1)}\n\n`;

    for (const [name, endpoint] of Object.entries(categoryEndpoints as any)) {
      const ep = endpoint as any;

      md += `#### \`${ep.method} ${ep.path}\`\n\n`;
      md += `${ep.description}\n\n`;

      md += `- **Server:** ${ep.server} (Port ${ep.port || 'N/A'})\n`;
      md += `- **Authentication:** ${ep.authentication}\n`;
      if (ep.apiGatewayPath) {
        md += `- **API Gateway Path:** \`${ep.apiGatewayPath}\`\n`;
      }
      md += '\n';

      if (ep.parameters) {
        md += '**Parameters:**\n\n';
        if (ep.parameters.path) {
          md += '*Path Parameters:*\n';
          for (const [paramName, paramSpec] of Object.entries(ep.parameters.path)) {
            const p = paramSpec as any;
            md += `- \`${paramName}\` (${p.type}${p.required ? ', required' : ''}): ${p.description}\n`;
          }
          md += '\n';
        }
        if (ep.parameters.query) {
          md += '*Query Parameters:*\n';
          for (const [paramName, paramSpec] of Object.entries(ep.parameters.query)) {
            const p = paramSpec as any;
            md += `- \`${paramName}\` (${p.type}${p.required ? ', required' : ', optional'}): ${p.description}\n`;
            if (p.enum) md += `  - Values: ${p.enum.join(', ')}\n`;
          }
          md += '\n';
        }
      }

      if (ep.requestBody) {
        md += '**Request Body:**\n\n';
        md += '```json\n';
        md += JSON.stringify(generateSchemaExample(ep.requestBody.schema), null, 2);
        md += '\n```\n\n';
      }

      if (ep.responses) {
        md += '**Responses:**\n\n';
        for (const [code, response] of Object.entries(ep.responses)) {
          const resp = response as any;
          md += `- **${code}**: ${resp.description}\n`;
          if (resp.example) {
            md += '  ```json\n';
            md += '  ' + JSON.stringify(resp.example, null, 2).split('\n').join('\n  ');
            md += '\n  ```\n';
          }
        }
        md += '\n';
      }

      md += '---\n\n';
    }
  }

  return md;
}

function generateSchemaExample(schema: any): any {
  if (!schema || !schema.properties) return {};

  const example: any = {};
  for (const [key, prop] of Object.entries(schema.properties)) {
    const p = prop as any;
    if (p.example) {
      example[key] = p.example;
    } else if (p.type === 'string') {
      example[key] = p.pattern ? 'pattern-value' : 'string-value';
    } else if (p.type === 'number') {
      example[key] = 123;
    } else if (p.type === 'boolean') {
      example[key] = true;
    } else if (p.type === 'array') {
      example[key] = [];
    } else if (p.type === 'object') {
      example[key] = generateSchemaExample(p);
    }
  }
  return example;
}

function generateErrorHandling(errorHandling: any): string {
  let md = '**Standard Error Response:**\n\n';
  md += '```json\n';
  md += JSON.stringify(generateSchemaExample(errorHandling.standardErrorResponse), null, 2);
  md += '\n```\n\n';

  md += '**Common HTTP Errors:**\n\n';
  for (const [code, description] of Object.entries(errorHandling.commonErrors)) {
    md += `- **${code}**: ${description}\n`;
  }
  md += '\n';

  return md;
}

function generateRateLimiting(rateLimiting: any): string {
  let md = '';

  for (const [name, limit] of Object.entries(rateLimiting)) {
    const l = limit as any;
    md += `**${name.toUpperCase()}:**\n`;
    md += `- ${l.description}\n`;
    if (l.appliesTo) {
      md += `- Applies To: ${Array.isArray(l.appliesTo) ? l.appliesTo.join(', ') : l.appliesTo}\n`;
    }
    md += '\n';
  }

  return md;
}

function generateSecuritySection(security: any): string {
  let md = '**Security Headers:**\n\n';
  for (const [header, value] of Object.entries(security.headers)) {
    md += `- **${header}**: \`${value}\`\n`;
  }
  md += '\n';

  md += '**Input Validation:**\n\n';
  for (const [type, description] of Object.entries(security.inputValidation)) {
    md += `- **${type}**: ${description}\n`;
  }
  md += '\n';

  return md;
}

function generateEnvironmentVariables(vars: any): string {
  let md = '';

  for (const [name, varSpec] of Object.entries(vars)) {
    const v = varSpec as any;
    md += `**\`${name}\`**\n`;
    md += `- Description: ${v.description}\n`;
    if (v.values) md += `- Values: ${v.values.join(', ')}\n`;
    if (v.format) md += `- Format: \`${v.format}\`\n`;
    if (v.default) md += `- Default: ${v.default}\n`;
    if (v.required) md += `- Required: ${v.required === true ? 'Yes' : v.required}\n`;
    if (v.generate) md += `- Generate: \`${v.generate}\`\n`;
    md += '\n';
  }

  return md;
}

function generateRelatedDocs(docs: any): string {
  let md = '';

  for (const [name, path] of Object.entries(docs)) {
    md += `- **${name}**: \`${path}\`\n`;
  }

  return md + '\n';
}

// Execute
generateAPIDocs().catch(console.error);
