#!/bin/bash
# Quick 503 fix reference card
# Copy-paste these commands directly

echo "==================================================="
echo "503 SERVICE UNAVAILABLE - QUICK FIX REFERENCE"
echo "==================================================="
echo ""
echo "SERVER: root@143.198.154.94"
echo "WORKING DIR: /var/www/ectropy"
echo ""
echo "==================================================="
echo "OPTION 1: AUTO FIX (RECOMMENDED)"
echo "==================================================="
echo ""
echo "ssh root@143.198.154.94 'cd /var/www/ectropy && bash -c \"\\"
echo "  docker compose -f docker-compose.staging.yml down && \\"
echo "  docker compose -f docker-compose.staging.yml up -d && \\"
echo "  sleep 30 && \\"
echo "  docker compose -f docker-compose.staging.yml ps && \\"
echo "  systemctl status nginx && \\"
echo "  curl -I https://staging.ectropy.ai\\"
echo "\"'"
echo ""
echo "==================================================="
echo "OPTION 2: USE DIAGNOSTIC SCRIPT"
echo "==================================================="
echo ""
echo "# Run remotely (no need to copy file):"
echo "ssh root@143.198.154.94 'bash -s' < scripts/diagnose-503-staging.sh"
echo ""
echo "# Or copy and run:"
echo "scp scripts/diagnose-503-staging.sh root@143.198.154.94:/tmp/"
echo "ssh root@143.198.154.94 '/tmp/diagnose-503-staging.sh auto'"
echo ""
echo "==================================================="
echo "OPTION 3: MANUAL COMMANDS"
echo "==================================================="
echo ""
echo "ssh root@143.198.154.94"
echo ""
echo "# Then run on server:"
echo "cd /var/www/ectropy"
echo "docker compose -f docker-compose.staging.yml ps"
echo "systemctl status nginx"
echo ""
echo "# If services are down:"
echo "docker compose -f docker-compose.staging.yml down"
echo "docker compose -f docker-compose.staging.yml up -d"
echo "sleep 30"
echo ""
echo "# If nginx is down:"
echo "systemctl start nginx"
echo ""
echo "# If mcp-server build failed (EOF error):"
echo "docker compose -f docker-compose.staging.yml build --no-cache mcp-server"
echo "docker compose -f docker-compose.staging.yml up -d"
echo ""
echo "# Validate fix:"
echo "curl http://localhost:4000/health"
echo "curl http://localhost:3002"
echo "curl http://localhost:3001/health"
echo "curl -I https://staging.ectropy.ai"
echo ""
echo "==================================================="
echo "VALIDATION CHECKLIST"
echo "==================================================="
echo ""
echo "✓ All services running: docker compose ps shows 'Up'"
echo "✓ Nginx active: systemctl status nginx shows 'active'"
echo "✓ API responds: curl http://localhost:4000/health returns 200"
echo "✓ Web responds: curl http://localhost:3002 returns 200"
echo "✓ MCP responds: curl http://localhost:3001/health returns 200"
echo "✓ Public works: curl -I https://staging.ectropy.ai returns 200"
echo ""
