#!/usr/bin/env node
/**
 * Local Environment Setup Script - Ectropy Platform
 * Sets up local development environment with GitHub Secrets integration
 */

import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';

console.log('🚀 Setting up local Ectropy development environment...\n');

// Check for GitHub CLI
let hasGitHubCLI = false;
try {
  execSync('gh auth status', { stdio: 'ignore' });
  console.log('✅ GitHub CLI authenticated');
  hasGitHubCLI = true;
  
  console.log('📝 GitHub Secrets Access:');
  console.log('   Contact repo admin to get access to secrets');
  console.log('   Then run: gh secret list --repo luhtech/Ectropy');
  console.log('');
  
  // Try to list secrets (will show if user has access)
  try {
    const secrets = execSync('gh secret list --repo luhtech/Ectropy', { encoding: 'utf8' });
    if (secrets.trim()) {
      console.log('🔑 Available GitHub Secrets:');
      console.log(secrets);
    }
  } catch (error) {
    console.log('⚠️  No access to GitHub Secrets (contact repo admin)');
  }
  
} catch (error) {
  console.log('⚠️  GitHub CLI not found or not authenticated');
  console.log('📦 Install GitHub CLI: https://cli.github.com/');
  console.log('🔑 Authenticate with: gh auth login');
}

console.log('📝 Creating .env.local with development defaults...\n');

// Create LOCAL ONLY defaults (not from GitHub Secrets)
const localDefaults = `# Ectropy Platform - Local Development Environment
# Generated by scripts/setup-local.js
# DO NOT COMMIT THIS FILE - Contains local development values only

# === NODE ENVIRONMENT ===
NODE_ENV=development

# === DATABASE CONFIGURATION ===
# These match docker-compose.local.yml service names
DATABASE_HOST=localhost
DATABASE_PORT=5432
DATABASE_NAME=ectropy_dev
DATABASE_USER=ectropy
DB_PASSWORD=localdev123

# === REDIS CONFIGURATION ===
REDIS_HOST=localhost
REDIS_PORT=6379
# REDIS_PASSWORD= # No password for local development

# === API GATEWAY ===
API_GATEWAY_PORT=4000
CORS_ORIGIN=http://localhost:3002

# === AUTHENTICATION (LOCAL ONLY - NOT FOR PRODUCTION) ===
JWT_SECRET=local_only_jwt_secret_not_for_production_use_32_chars
SESSION_SECRET=local_session_secret_for_development_only_change_for_prod

# === FRONTEND CONFIGURATION ===
REACT_APP_API_URL=http://localhost:4000
REACT_APP_SPECKLE_URL=http://localhost:3000

# === LOGGING & MONITORING ===
LOG_LEVEL=debug
ENABLE_METRICS=true

# === FEATURE FLAGS (DEVELOPMENT) ===
ENABLE_REALTIME=true
ENABLE_BIM_VIEWER=true
ENABLE_ANALYTICS=false
ENABLE_BLOCKCHAIN=false
ENABLE_AI_AGENTS=false

# =========================================
# FOR PRODUCTION VALUES:
# Contact repository admin for GitHub Secrets access
# =========================================
`;

const envLocalPath = path.join(process.cwd(), '.env.local');
fs.writeFileSync(envLocalPath, localDefaults.trim());

console.log('✅ Created .env.local with LOCAL development defaults');
console.log('📁 File location: .env.local');
console.log('');

if (!hasGitHubCLI) {
  console.log('💡 To use production values:');
  console.log('   1. Install GitHub CLI: https://cli.github.com/');
  console.log('   2. Authenticate: gh auth login');
  console.log('   3. Contact repo admin for secrets access');
  console.log('   4. Re-run this script');
} else {
  console.log('💡 To get production values:');
  console.log('   1. Contact repo admin for GitHub Secrets access');
  console.log('   2. Run: gh secret list --repo luhtech/Ectropy');
  console.log('   3. Manually update .env.local with production values if needed');
}

console.log('');
console.log('🎯 Next steps:');
console.log('   1. Start services: npm run docker:start');
console.log('   2. Start development servers:');
console.log('      - MCP Server: npm run dev:mcp');
console.log('      - API Gateway: npm run dev:api');
console.log('      - Web Dashboard: npm run dev:web');

console.log('\n✅ Local environment setup completed!');