# ============================================================================
# Dedicated Tenant Database Module - Outputs
# ============================================================================
# Phase 7 - Enterprise Dedicated Database Provisioning
#
# These outputs provide database connection details for:
# 1. Tenant registry updates (platform DB)
# 2. Application configuration (DATABASE_URL)
# 3. Prisma migrations
# 4. Monitoring and observability
# ============================================================================

# ============================================================================
# Database Cluster Identification
# ============================================================================

output "cluster_id" {
  description = "Database cluster ID (for DigitalOcean API operations)"
  value       = digitalocean_database_cluster.tenant_database.id
}

output "cluster_urn" {
  description = "Database cluster URN (unique resource name for cross-resource references)"
  value       = digitalocean_database_cluster.tenant_database.urn
}

output "cluster_name" {
  description = "Database cluster name (ectropy-{tenant_slug}-db)"
  value       = digitalocean_database_cluster.tenant_database.name
}

# ============================================================================
# Database Connection Details
# ============================================================================

output "database_name" {
  description = "Database name within cluster (ectropy_{tenant_slug})"
  value       = digitalocean_database_db.tenant_database_db.name
}

output "database_host" {
  description = "Database host (private network preferred for security)"
  value       = digitalocean_database_cluster.tenant_database.private_host
  sensitive   = true
}

output "database_port" {
  description = "Database port (default: 25060)"
  value       = digitalocean_database_cluster.tenant_database.port
}

output "database_user" {
  description = "Database user for application ({tenant_slug}_app)"
  value       = digitalocean_database_user.tenant_app_user.name
  sensitive   = true
}

output "database_password" {
  description = "Database password for application user (auto-generated by DigitalOcean)"
  value       = digitalocean_database_user.tenant_app_user.password
  sensitive   = true
}

# ============================================================================
# Connection URIs
# ============================================================================

output "database_uri" {
  description = "Full database connection URI (private network, direct connection)"
  value       = digitalocean_database_cluster.tenant_database.private_uri
  sensitive   = true
}

output "database_uri_pool" {
  description = "Connection pool URI (if connection pooling enabled, otherwise null)"
  value = var.enable_connection_pool ? (
    length(digitalocean_database_connection_pool.tenant_pool) > 0 ?
    digitalocean_database_connection_pool.tenant_pool[0].private_uri :
    null
  ) : null
  sensitive = true
}

output "connection_string" {
  description = "Prisma-compatible connection string (DATABASE_URL format)"
  value = format(
    "postgresql://%s:%s@%s:%s/%s?schema=public&sslmode=require",
    digitalocean_database_user.tenant_app_user.name,
    digitalocean_database_user.tenant_app_user.password,
    digitalocean_database_cluster.tenant_database.private_host,
    digitalocean_database_cluster.tenant_database.port,
    digitalocean_database_db.tenant_database_db.name
  )
  sensitive = true
}

output "connection_string_pool" {
  description = "Prisma-compatible connection string using connection pool (if enabled)"
  value = var.enable_connection_pool && length(digitalocean_database_connection_pool.tenant_pool) > 0 ? format(
    "postgresql://%s:%s@%s:%s/%s?schema=public&sslmode=require&pgbouncer=true",
    digitalocean_database_user.tenant_app_user.name,
    digitalocean_database_user.tenant_app_user.password,
    digitalocean_database_connection_pool.tenant_pool[0].private_host,
    digitalocean_database_connection_pool.tenant_pool[0].port,
    digitalocean_database_db.tenant_database_db.name
  ) : null
  sensitive = true
}

# ============================================================================
# Cluster Metadata (for tenant registry)
# ============================================================================

output "cluster_metadata" {
  description = "Database cluster metadata for tenant registry database_connections table"
  value = {
    cluster_id      = digitalocean_database_cluster.tenant_database.id
    cluster_urn     = digitalocean_database_cluster.tenant_database.urn
    database_name   = digitalocean_database_db.tenant_database_db.name
    database_host   = digitalocean_database_cluster.tenant_database.private_host
    database_port   = digitalocean_database_cluster.tenant_database.port
    database_user   = digitalocean_database_user.tenant_app_user.name
    engine          = digitalocean_database_cluster.tenant_database.engine
    version         = digitalocean_database_cluster.tenant_database.version
    region          = digitalocean_database_cluster.tenant_database.region
    node_count      = digitalocean_database_cluster.tenant_database.node_count
    size            = digitalocean_database_cluster.tenant_database.size
    status          = digitalocean_database_cluster.tenant_database.status
    created_at      = digitalocean_database_cluster.tenant_database.created_at
    connection_pool = var.enable_connection_pool
  }
  sensitive = true
}

# ============================================================================
# High Availability Details
# ============================================================================

output "high_availability" {
  description = "High availability configuration details"
  value = {
    enabled       = var.node_count > 1
    node_count    = var.node_count
    standby_nodes = var.node_count - 1
  }
}

# ============================================================================
# Connection Pool Details
# ============================================================================

output "connection_pool_details" {
  description = "Connection pool configuration (if enabled)"
  value = var.enable_connection_pool && length(digitalocean_database_connection_pool.tenant_pool) > 0 ? {
    enabled    = true
    pool_name  = digitalocean_database_connection_pool.tenant_pool[0].name
    pool_size  = var.connection_pool_size
    pool_mode  = digitalocean_database_connection_pool.tenant_pool[0].mode
    pool_host  = digitalocean_database_connection_pool.tenant_pool[0].private_host
    pool_port  = digitalocean_database_connection_pool.tenant_pool[0].port
  } : {
    enabled = false
  }
  sensitive = true
}

# ============================================================================
# Security Details
# ============================================================================

output "security_configuration" {
  description = "Security and firewall configuration summary"
  value = {
    firewall_ip_count  = length(var.firewall_allowed_ips)
    firewall_tag_count = length(var.firewall_allowed_tags)
    ssl_required       = true
    network_type       = "private"
  }
}

# ============================================================================
# Maintenance Configuration
# ============================================================================

output "maintenance_window" {
  description = "Maintenance window configuration"
  value = {
    day  = var.maintenance_window_day
    hour = var.maintenance_window_hour
    timezone = "UTC"
  }
}

# ============================================================================
# Backup Configuration
# ============================================================================

output "backup_configuration" {
  description = "Backup retention configuration"
  value = {
    retention_days = var.backup_retention_days
    automated      = true
  }
}

# ============================================================================
# Provisioning Summary
# ============================================================================

output "provisioning_summary" {
  description = "Human-readable provisioning summary (for Terraform output display)"
  value = <<-EOT
    ✅ Dedicated Database Provisioned
    ================================
    Tenant: ${var.tenant_slug}
    Database: ectropy_${replace(var.tenant_slug, "-", "_")}
    Cluster: ${digitalocean_database_cluster.tenant_database.name}

    Configuration:
    - PostgreSQL ${var.postgres_version}
    - Size: ${var.database_size}
    - Region: ${var.region}
    - Nodes: ${var.node_count}${var.node_count > 1 ? " (HA enabled)" : ""}
    - Connection Pool: ${var.enable_connection_pool ? "Enabled (${var.connection_pool_size} connections)" : "Disabled"}

    Connection Info:
    - Host: ${digitalocean_database_cluster.tenant_database.private_host}
    - Port: ${digitalocean_database_cluster.tenant_database.port}
    - User: ${digitalocean_database_user.tenant_app_user.name}
    - Database: ${digitalocean_database_db.tenant_database_db.name}

    Security:
    - Firewall: ${length(var.firewall_allowed_ips)} IP(s), ${length(var.firewall_allowed_tags)} tag(s)
    - SSL: Required
    - Network: Private

    Maintenance:
    - Day: ${var.maintenance_window_day}
    - Time: ${var.maintenance_window_hour} UTC
    - Backups: ${var.backup_retention_days} days

    Next Steps:
    1. Update tenant registry with database connection metadata
    2. Run Prisma migrations: npx prisma migrate deploy
    3. Test database connectivity from app servers
    4. Configure application DATABASE_URL environment variable
    5. Monitor database performance and adjust size if needed
  EOT
}
