#!/bin/bash
# Tenant-Specific Droplet Initialization Script
# Generated by Terraform for tenant: ${tenant_id}

set -e

echo "=========================================="
echo "Initializing Ectropy Tenant Infrastructure"
echo "=========================================="
echo "Tenant ID: ${tenant_id}"
echo "Tenant Name: ${tenant_name}"
echo "Data Residency Region: ${region}"
echo "=========================================="

# Update system
apt-get update
apt-get upgrade -y

# Install Docker
curl -fsSL https://get.docker.com -o get-docker.sh
sh get-docker.sh
systemctl enable docker
systemctl start docker

# Install Docker Compose
curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose

# Create application directory
mkdir -p /opt/ectropy
cd /opt/ectropy

# Set tenant metadata
cat > /opt/ectropy/tenant-metadata.json <<EOF
{
  "tenant_id": "${tenant_id}",
  "tenant_name": "${tenant_name}",
  "data_residency_region": "${region}",
  "isolation_tier": "dedicated",
  "provisioned_at": "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
}
EOF

echo "✅ Tenant infrastructure initialized successfully"
echo "Next: Deploy application via CI/CD pipeline"
