/**
 * ============================================================================
 * MULTI-TRADE COORDINATION SCENARIO
 * ============================================================================
 * Demonstrates complex coordination between multiple trades working
 * simultaneously on overlapping work areas.
 *
 * Scenario Highlights:
 * - 4 trades working in same zones
 * - Scheduling conflicts and resolutions
 * - Material delivery coordination
 * - Quality control checkpoints
 * - Real-time progress tracking
 *
 * @module @ectropy/demo-scenarios/scenarios
 * @version 1.0.0
 * ============================================================================
 */

import type {
  DemoScenario,
  ScenarioEvent,
  ScenarioMilestone,
  Persona,
  // TimelinePosition, // Unused import
  BuildingType,
} from '../types/index.js';
import {
  createArchitectPersona,
  createEngineerPersona,
  createContractorPersona,
  createOwnerPersona,
} from '../personas/index.js';

// ============================================================================
// ADDITIONAL PERSONAS FOR MULTI-TRADE
// ============================================================================

/**
 * MEP (Mechanical/Electrical/Plumbing) Coordinator
 */
const mepCoordinatorPersona: Persona = {
  id: 'mep-coordinator-001',
  name: 'Chris Martinez',
  email: 'chris.martinez@mepservices.com',
  role: 'engineer',
  company: 'MEP Services Inc.',
  avatar: '/avatars/chris-martinez.jpg',
  permissions: [
    'view_project',
    'edit_elements',
    'submit_rfi',
    'review_submittals',
    'manage_scheduling',
  ],
  behaviorProfile: {
    responseSpeed: 0.75,
    thoroughness: 0.9,
    escalationTendency: 0.6,
    workingHours: { start: 6, end: 16 },
    communicationStyle: 'technical',
    decisionPatterns: ['data-driven', 'coordination-focused'],
  },
};

/**
 * Electrical Foreman
 */
const electricalForemanPersona: Persona = {
  id: 'electrical-foreman-001',
  name: 'James Wilson',
  email: 'james.wilson@voltelectric.com',
  role: 'contractor',
  company: 'Volt Electric Co.',
  avatar: '/avatars/james-wilson.jpg',
  permissions: [
    'view_project',
    'edit_elements',
    'update_progress',
    'report_issues',
  ],
  behaviorProfile: {
    responseSpeed: 0.85,
    thoroughness: 0.8,
    escalationTendency: 0.5,
    workingHours: { start: 6, end: 15 },
    communicationStyle: 'direct',
    decisionPatterns: ['practical', 'safety-first'],
  },
};

/**
 * Plumbing Foreman
 */
const plumbingForemanPersona: Persona = {
  id: 'plumbing-foreman-001',
  name: 'Roberto Garcia',
  email: 'roberto.garcia@flowplumbing.com',
  role: 'contractor',
  company: 'Flow Plumbing Systems',
  avatar: '/avatars/roberto-garcia.jpg',
  permissions: [
    'view_project',
    'edit_elements',
    'update_progress',
    'report_issues',
  ],
  behaviorProfile: {
    responseSpeed: 0.8,
    thoroughness: 0.85,
    escalationTendency: 0.4,
    workingHours: { start: 6, end: 15 },
    communicationStyle: 'collaborative',
    decisionPatterns: ['experience-based', 'team-oriented'],
  },
};

/**
 * HVAC Foreman
 */
const hvacForemanPersona: Persona = {
  id: 'hvac-foreman-001',
  name: 'Kevin Thompson',
  email: 'kevin.thompson@climatecontrol.com',
  role: 'contractor',
  company: 'Climate Control HVAC',
  avatar: '/avatars/kevin-thompson.jpg',
  permissions: [
    'view_project',
    'edit_elements',
    'update_progress',
    'report_issues',
  ],
  behaviorProfile: {
    responseSpeed: 0.7,
    thoroughness: 0.9,
    escalationTendency: 0.55,
    workingHours: { start: 7, end: 16 },
    communicationStyle: 'technical',
    decisionPatterns: ['methodical', 'specification-driven'],
  },
};

// ============================================================================
// SCENARIO DEFINITION
// ============================================================================

/**
 * Creates the Multi-Trade Coordination scenario
 */
export function createMultiTradeScenario(projectId: string): DemoScenario {
  // Core personas
  const architect = createArchitectPersona(projectId);
  const engineer = createEngineerPersona(projectId);
  const gcContractor = createContractorPersona(projectId);
  const owner = createOwnerPersona(projectId);

  const personas: Persona[] = [
    architect,
    engineer,
    gcContractor,
    owner,
    mepCoordinatorPersona,
    electricalForemanPersona,
    plumbingForemanPersona,
    hvacForemanPersona,
  ];

  // ============================================================================
  // MILESTONES
  // ============================================================================

  const milestones: ScenarioMilestone[] = [
    {
      id: 'mt-milestone-kickoff',
      name: 'Trade Coordination Kickoff',
      position: { week: 1, day: 1, hour: 9 },
      description: 'All trades meet to review coordination requirements',
      highlightedEvents: ['mt-event-001'],
      presenterNotes: [
        'DEMO POINT: Show the complexity of 4 trades in same space',
        'Highlight how Ectropy visualizes overlap zones',
        'Introduce the scheduling conflict detection feature',
      ],
      expectedOutcome:
        'All trades aligned on sequence and zone access schedule',
    },
    {
      id: 'mt-milestone-conflict',
      name: 'First Scheduling Conflict',
      position: { week: 2, day: 3, hour: 10 },
      description: 'Electrical and plumbing crews discover routing conflict',
      highlightedEvents: ['mt-event-009', 'mt-event-010'],
      presenterNotes: [
        'DEMO POINT: Real-time conflict detection in action',
        'Show how system alerts all affected parties immediately',
        'Demonstrate proposed resolution workflow',
      ],
      expectedOutcome: 'Conflict identified, resolution options generated',
    },
    {
      id: 'mt-milestone-resolution',
      name: 'Conflict Resolution Complete',
      position: { week: 2, day: 5, hour: 14 },
      description: 'MEP coordinator brokers solution with rerouting',
      highlightedEvents: ['mt-event-012', 'mt-event-015', 'mt-event-016'],
      presenterNotes: [
        'DEMO POINT: Authority cascade for conflict resolution',
        'Show voting/approval workflow for schedule changes',
        'Highlight impact analysis on downstream trades',
      ],
      expectedOutcome: 'Approved rerouting plan with updated schedule',
    },
    {
      id: 'mt-milestone-inspection',
      name: 'Coordinated Inspection',
      position: { week: 4, day: 2, hour: 9 },
      description: 'Joint MEP rough-in inspection',
      highlightedEvents: ['mt-event-023', 'mt-event-024'],
      presenterNotes: [
        'DEMO POINT: Multi-trade inspection coordination',
        'Show how all systems are inspected together efficiently',
        'Demonstrate digital inspection checklist and sign-off',
      ],
      expectedOutcome: 'All MEP rough-in work approved for close-in',
    },
    {
      id: 'mt-milestone-completion',
      name: 'Phase Complete',
      position: { week: 6, day: 5, hour: 16 },
      description: 'All trades complete zone work, ready for drywall',
      highlightedEvents: ['mt-event-030'],
      presenterNotes: [
        'DEMO POINT: Successful multi-trade coordination outcome',
        'Show time saved vs traditional coordination methods',
        'Highlight zero rework due to conflicts',
      ],
      expectedOutcome: 'Zone cleared for next phase, all trades released',
    },
  ];

  // ============================================================================
  // TIMELINE EVENTS
  // ============================================================================

  const timeline: ScenarioEvent[] = [
    // Week 1: Kickoff and initial setup
    {
      id: 'mt-event-001',
      urn: 'urn:ectropy:event:mt-event-001',
      type: 'meeting',
      position: { week: 1, day: 1, hour: 9 },
      actor: 'contractor',
      persona: 'gc-multi-001',
      priority: 'normal',
      title: 'Trade Coordination Kickoff Meeting',
      description: 'GC calls coordination meeting for all trade foremen',
      voxelRefs: [],
      decisionRefs: [],
      payload: {
        type: 'meeting',
        meetingType: 'coordination',
        attendees: [
          'mep-coordinator-001',
          'electrical-foreman-001',
          'plumbing-foreman-001',
          'hvac-foreman-001',
        ],
        agenda: ['Zone assignments', 'Scheduling sequence', 'Material staging'],
      },
      consequences: [],
      triggeredEvents: [],
      metadata: {
        probability: 1.0,
        dependencies: [],
        skippable: false,
        interactive: true,
        emphasis: 'highlighted',
      },
      data: {
        meetingType: 'coordination',
        attendees: [
          'mep-coordinator-001',
          'electrical-foreman-001',
          'plumbing-foreman-001',
          'hvac-foreman-001',
        ],
        agenda: ['Zone assignments', 'Scheduling sequence', 'Material staging'],
      },
    },
    {
      id: 'mt-event-002',
      urn: 'urn:ectropy:event:mt-event-002',
      type: 'schedule_update',
      position: { week: 1, day: 1, hour: 14 },
      actor: 'contractor',
      persona: 'mep-coordinator-001',
      priority: 'high',
      title: 'Master Coordination Schedule Published',
      description: 'MEP coordinator publishes master coordination schedule',
      voxelRefs: [],
      decisionRefs: [],
      payload: {} as any,
      consequences: [],
      triggeredEvents: [],
      metadata: {
        probability: 1.0,
        dependencies: ['mt-event-001'],
        skippable: false,
        interactive: false,
        emphasis: 'normal',
      },
      data: {
        scheduleType: 'coordination',
        zones: ['Zone A - Floors 1-2', 'Zone B - Floors 3-4'],
        sequence: 'Plumbing first, HVAC second, Electrical third',
      },
    },
    {
      id: 'mt-event-003',
      urn: 'urn:ectropy:event:mt-event-003',
      type: 'upload',
      position: { week: 1, day: 2, hour: 8 },
      actor: 'contractor',
      persona: 'plumbing-foreman-001',
      priority: 'normal',
      title: 'Plumbing Zone A Rough-in Started',
      description: 'Plumbing crew begins Zone A rough-in',
      voxelRefs: [],
      decisionRefs: [],
      payload: {
        type: 'upload',
        fileType: 'pdf',
        fileName: 'progress-report.pdf',
        fileSize: 1024,
        description: 'Plumbing crew begins Zone A rough-in',
      },
      consequences: [],
      triggeredEvents: [],
      metadata: {
        probability: 1.0,
        dependencies: ['mt-event-002'],
        skippable: false,
        interactive: false,
        emphasis: 'normal',
      },
      data: {
        progressType: 'start',
        zone: 'Zone A',
        workType: 'Domestic water and drain rough-in',
        crewSize: 6,
      },
    },
    {
      id: 'mt-event-004',
      urn: 'urn:ectropy:event:mt-event-004',
      type: 'upload',
      position: { week: 1, day: 3, hour: 7 },
      actor: 'contractor',
      persona: 'hvac-foreman-001',
      priority: 'normal',
      title: 'HVAC Ductwork Fabrication Started',
      description: 'HVAC ductwork fabrication begins',
      voxelRefs: [],
      decisionRefs: [],
      payload: {
        type: 'upload',
        fileType: 'pdf',
        fileName: 'progress-report.pdf',
        fileSize: 1024,
        description: 'HVAC ductwork fabrication begins',
      },
      consequences: [],
      triggeredEvents: [],
      metadata: {
        probability: 1.0,
        dependencies: [],
        skippable: false,
        interactive: false,
        emphasis: 'normal',
      },
      data: {
        progressType: 'fabrication',
        workType: 'Main trunk duct fabrication',
        location: 'Shop/staging area',
      },
    },
    {
      id: 'mt-event-005',
      urn: 'urn:ectropy:event:mt-event-005',
      type: 'progress',
      position: { week: 1, day: 4, hour: 15 },
      actor: 'contractor',
      persona: 'plumbing-foreman-001',
      priority: 'normal',
      title: 'Plumbing Progress Update - 30%',
      description: 'Plumbing 30% complete in Zone A',
      voxelRefs: [],
      decisionRefs: [],
      payload: {
        type: 'progress',
        workCompleted: 'Plumbing rough-in',
        percentComplete: 30,
        phase: 'rough_in',
        notes: 'On schedule, no issues',
      },
      consequences: [],
      triggeredEvents: [],
      metadata: {
        probability: 1.0,
        dependencies: ['mt-event-003'],
        skippable: true,
        interactive: false,
        emphasis: 'normal',
      },
      data: {
        progressPercent: 30,
        zone: 'Zone A',
        notes: 'On schedule, no issues',
      },
    },
    {
      id: 'mt-event-006',
      urn: 'urn:ectropy:event:mt-event-006',
      type: 'upload',
      position: { week: 1, day: 5, hour: 8 },
      actor: 'contractor',
      persona: 'electrical-foreman-001',
      priority: 'normal',
      title: 'Electrical Material Delivery',
      description: 'Electrical material delivery to site',
      voxelRefs: [],
      decisionRefs: [],
      payload: {
        type: 'upload',
        fileType: 'pdf',
        fileName: 'delivery-report.pdf',
        fileSize: 1024,
        description: 'Electrical material delivery to site',
      },
      consequences: [],
      triggeredEvents: [],
      metadata: {
        probability: 1.0,
        dependencies: [],
        skippable: false,
        interactive: false,
        emphasis: 'normal',
      },
      data: {
        deliveryType: 'material',
        items: ['Wire spools', 'Conduit', 'Boxes', 'Panel components'],
        stagingLocation: 'Zone B staging area',
      },
    },

    // Week 2: Conflict emerges
    {
      id: 'mt-event-007',
      urn: 'urn:ectropy:event:mt-event-007',
      type: 'progress',
      position: { week: 2, day: 1, hour: 10 },
      actor: 'contractor',
      persona: 'plumbing-foreman-001',
      priority: 'normal',
      title: 'Plumbing Progress Update - 60%',
      description: 'Plumbing 60% complete in Zone A',
      voxelRefs: [],
      decisionRefs: [],
      payload: {
        type: 'progress',
        workCompleted: 'Plumbing rough-in',
        percentComplete: 60,
        phase: 'rough_in',
        notes: 'Main stacks installed, branches starting',
      },
      consequences: [],
      triggeredEvents: [],
      metadata: {
        probability: 1.0,
        dependencies: ['mt-event-005'],
        skippable: true,
        interactive: false,
        emphasis: 'normal',
      },
      data: {
        progressPercent: 60,
        zone: 'Zone A',
        notes: 'Main stacks installed, branches starting',
      },
    },
    {
      id: 'mt-event-008',
      urn: 'urn:ectropy:event:mt-event-008',
      type: 'upload',
      position: { week: 2, day: 1, hour: 11 },
      actor: 'contractor',
      persona: 'electrical-foreman-001',
      priority: 'normal',
      title: 'Electrical Zone A Conduit Routing Started',
      description: 'Electrical begins Zone A conduit routing',
      voxelRefs: [],
      decisionRefs: [],
      payload: {
        type: 'upload',
        fileType: 'pdf',
        fileName: 'progress-report.pdf',
        fileSize: 1024,
        description: 'Electrical begins Zone A conduit routing',
      },
      consequences: [],
      triggeredEvents: [],
      metadata: {
        probability: 1.0,
        dependencies: ['mt-event-006'],
        skippable: false,
        interactive: false,
        emphasis: 'normal',
      },
      data: {
        progressType: 'start',
        zone: 'Zone A',
        workType: 'Main conduit runs',
      },
    },
    {
      id: 'mt-event-009',
      urn: 'urn:ectropy:event:mt-event-009',
      type: 'issue',
      position: { week: 2, day: 3, hour: 10 },
      actor: 'contractor',
      persona: 'electrical-foreman-001',
      priority: 'critical',
      title: 'Routing Conflict Detected',
      description: '**CONFLICT DETECTED** Conduit route blocked by plumbing',
      voxelRefs: [],
      decisionRefs: [],
      payload: {
        type: 'issue',
        issueType: 'coordination',
        severity: 'high',
        description:
          '4-inch drain line occupies planned conduit chase. 2-inch clearance violation.',
      },
      consequences: [
        {
          category: 'COORDINATION_CONFLICT',
          description: 'Electrical conduit route blocked by plumbing',
          severity: 'high',
        },
      ],
      triggeredEvents: ['mt-event-010'],
      metadata: {
        probability: 1.0,
        dependencies: ['mt-event-008'],
        skippable: false,
        interactive: true,
        emphasis: 'critical',
      },
      data: {
        issueType: 'routing_conflict',
        severity: 'high',
        location: 'Zone A, Corridor 2, ceiling space',
        conflictingTrade: 'plumbing',
        description:
          '4-inch drain line occupies planned conduit chase. 2-inch clearance violation.',
      },
    },
    {
      id: 'mt-event-010',
      urn: 'urn:ectropy:event:mt-event-010',
      type: 'notification',
      position: { week: 2, day: 3, hour: 10 },
      actor: 'system',
      persona: 'mep-coordinator-001',
      priority: 'high',
      title: 'Routing Conflict Alert',
      description: 'System alerts MEP coordinator of routing conflict',
      voxelRefs: [],
      decisionRefs: [],
      payload: {
        type: 'alert',
        alertType: 'coordination_conflict',
        severity: 'critical',
        message: 'Routing conflict detected between electrical and plumbing',
        requiresAcknowledgment: true,
      },
      consequences: [],
      triggeredEvents: ['mt-event-011'],
      metadata: {
        probability: 1.0,
        dependencies: ['mt-event-009'],
        skippable: false,
        interactive: false,
        emphasis: 'highlighted',
      },
      data: {
        notificationType: 'conflict_alert',
        priority: 'urgent',
        affectedParties: ['plumbing-foreman-001', 'electrical-foreman-001'],
        recommendedAction: 'Schedule coordination review',
      },
    },
    {
      id: 'mt-event-011',
      urn: 'urn:ectropy:event:mt-event-011',
      type: 'meeting',
      position: { week: 2, day: 3, hour: 14 },
      actor: 'contractor',
      persona: 'mep-coordinator-001',
      priority: 'high',
      title: 'Emergency Coordination Meeting',
      description: 'Emergency coordination meeting called',
      voxelRefs: [],
      decisionRefs: [],
      payload: {
        type: 'meeting',
        meetingType: 'coordination',
        attendees: [
          'electrical-foreman-001',
          'plumbing-foreman-001',
          'arch-multi-001',
        ],
        agenda: [
          'Review conflict',
          'Evaluate options',
          'Determine resolution path',
        ],
      },
      consequences: [],
      triggeredEvents: ['mt-event-012'],
      metadata: {
        probability: 1.0,
        dependencies: ['mt-event-010'],
        skippable: false,
        interactive: true,
        emphasis: 'highlighted',
      },
      data: {
        meetingType: 'conflict_resolution',
        attendees: [
          'electrical-foreman-001',
          'plumbing-foreman-001',
          'arch-multi-001',
        ],
        agenda: [
          'Review conflict',
          'Evaluate options',
          'Determine resolution path',
        ],
      },
    },
    {
      id: 'mt-event-012',
      urn: 'urn:ectropy:event:mt-event-012',
      type: 'decision',
      position: { week: 2, day: 4, hour: 9 },
      actor: 'contractor',
      persona: 'mep-coordinator-001',
      priority: 'high',
      title: 'Conflict Resolution Decision',
      description: 'Proposes 3 resolution options for team vote',
      voxelRefs: [],
      decisionRefs: [],
      payload: {
        type: 'decision',
        decisionType: 'DIRECTION',
        question: 'Select resolution option for routing conflict',
        options: [
          {
            id: 'opt-1',
            description: 'Reroute electrical 6 inches south',
            consequences: [],
            estimatedCost: 1200,
            estimatedDelay: 4,
          },
          {
            id: 'opt-2',
            description: 'Lower plumbing with offset fitting',
            consequences: [],
            estimatedCost: 800,
            estimatedDelay: 6,
          },
          {
            id: 'opt-3',
            description: 'Create shared chase with coordination',
            consequences: [],
            estimatedCost: 500,
            estimatedDelay: 2,
            recommended: true,
          },
        ],
        authorityRequired: 3,
      },
      consequences: [],
      triggeredEvents: ['mt-event-013', 'mt-event-014'],
      metadata: {
        probability: 1.0,
        dependencies: ['mt-event-011'],
        skippable: false,
        interactive: true,
        emphasis: 'highlighted',
      },
      data: {
        decisionType: 'conflict_resolution',
        options: [
          {
            id: 'opt-1',
            description: 'Reroute electrical 6 inches south',
            cost: 1200,
            delay: '4 hours',
          },
          {
            id: 'opt-2',
            description: 'Lower plumbing with offset fitting',
            cost: 800,
            delay: '6 hours',
          },
          {
            id: 'opt-3',
            description: 'Create shared chase with coordination',
            cost: 500,
            delay: '2 hours',
          },
        ],
        votingDeadline: '2 hours',
      },
    },
    {
      id: 'mt-event-013',
      urn: 'urn:ectropy:event:mt-event-013',
      type: 'vote',
      position: { week: 2, day: 4, hour: 11 },
      actor: 'contractor',
      persona: 'electrical-foreman-001',
      priority: 'high',
      title: 'Electrical Foreman Vote',
      description: 'Votes for Option 3 (shared chase)',
      voxelRefs: [],
      decisionRefs: ['mt-event-012'],
      payload: {
        type: 'vote',
        subject: 'Routing conflict resolution',
        options: ['opt-1', 'opt-2', 'opt-3'],
        voters: ['contractor'],
        deadline: { week: 2, day: 4, hour: 12 },
        result: 'opt-3',
      },
      consequences: [],
      triggeredEvents: [],
      metadata: {
        probability: 1.0,
        dependencies: ['mt-event-012'],
        skippable: false,
        interactive: true,
        emphasis: 'normal',
      },
      data: {
        selectedOption: 'opt-3',
        reason: 'Fastest resolution, maintains schedule',
      },
    },
    {
      id: 'mt-event-014',
      urn: 'urn:ectropy:event:mt-event-014',
      type: 'vote',
      position: { week: 2, day: 4, hour: 11 },
      actor: 'contractor',
      persona: 'plumbing-foreman-001',
      priority: 'high',
      title: 'Plumbing Foreman Vote',
      description: 'Votes for Option 3 (shared chase)',
      voxelRefs: [],
      decisionRefs: ['mt-event-012'],
      payload: {
        type: 'vote',
        subject: 'Routing conflict resolution',
        options: ['opt-1', 'opt-2', 'opt-3'],
        voters: ['contractor'],
        deadline: { week: 2, day: 4, hour: 12 },
        result: 'opt-3',
      },
      consequences: [],
      triggeredEvents: ['mt-event-015'],
      metadata: {
        probability: 1.0,
        dependencies: ['mt-event-012'],
        skippable: false,
        interactive: true,
        emphasis: 'normal',
      },
      data: {
        selectedOption: 'opt-3',
        reason: 'No rework needed on installed piping',
      },
    },
    {
      id: 'mt-event-015',
      urn: 'urn:ectropy:event:mt-event-015',
      type: 'approval',
      position: { week: 2, day: 5, hour: 9 },
      actor: 'architect',
      persona: 'arch-multi-001',
      priority: 'high',
      title: 'Shared Chase Design Approved',
      description: 'Architect approves shared chase design',
      voxelRefs: [],
      decisionRefs: ['mt-event-012'],
      payload: {
        type: 'approval',
        approvalType: 'decision',
        approvedBy: 'architect',
        conditions: ['Maintain fire separation', 'Access panel required'],
      },
      consequences: [],
      triggeredEvents: ['mt-event-016'],
      metadata: {
        probability: 1.0,
        dependencies: ['mt-event-014'],
        skippable: false,
        interactive: true,
        emphasis: 'highlighted',
      },
      data: {
        approvalType: 'design_change',
        reference: 'ASK-2024-047',
        conditions: ['Maintain fire separation', 'Access panel required'],
      },
    },
    {
      id: 'mt-event-016',
      urn: 'urn:ectropy:event:mt-event-016',
      type: 'progress',
      position: { week: 2, day: 5, hour: 14 },
      actor: 'contractor',
      persona: 'mep-coordinator-001',
      priority: 'normal',
      title: 'Conflict Resolved',
      description: 'Conflict resolved - shared chase installed',
      voxelRefs: [],
      decisionRefs: ['mt-event-012'],
      payload: {
        type: 'progress',
        workCompleted: 'Shared chase installation',
        percentComplete: 100,
        phase: 'rough_in',
        notes: 'Pre-installation BIM clash detection recommended',
      },
      consequences: [],
      triggeredEvents: [],
      metadata: {
        probability: 1.0,
        dependencies: ['mt-event-015'],
        skippable: false,
        interactive: false,
        emphasis: 'highlighted',
      },
      data: {
        resolutionComplete: true,
        actualDelay: '2.5 hours',
        costImpact: 550,
        lessonsLearned: 'Pre-installation BIM clash detection recommended',
      },
    },

    // Week 3: Recovery and progress
    {
      id: 'mt-event-017',
      urn: 'urn:ectropy:event:mt-event-017',
      type: 'progress',
      position: { week: 3, day: 1, hour: 16 },
      actor: 'contractor',
      persona: 'plumbing-foreman-001',
      priority: 'normal',
      title: 'Plumbing Zone A Complete',
      description: 'Plumbing 100% complete in Zone A',
      voxelRefs: [],
      decisionRefs: [],
      payload: {
        type: 'progress',
        workCompleted: 'Plumbing rough-in',
        percentComplete: 100,
        phase: 'rough_in',
        notes: 'All rough-in complete, ready for inspection',
      },
      consequences: [],
      triggeredEvents: [],
      metadata: {
        probability: 1.0,
        dependencies: ['mt-event-016'],
        skippable: false,
        interactive: false,
        emphasis: 'normal',
      },
      data: {
        progressPercent: 100,
        zone: 'Zone A',
        notes: 'All rough-in complete, ready for inspection',
      },
    },
    {
      id: 'mt-event-018',
      urn: 'urn:ectropy:event:mt-event-018',
      type: 'upload',
      position: { week: 3, day: 2, hour: 8 },
      actor: 'contractor',
      persona: 'hvac-foreman-001',
      priority: 'normal',
      title: 'HVAC Zone A Duct Installation Started',
      description: 'HVAC begins Zone A duct installation',
      voxelRefs: [],
      decisionRefs: [],
      payload: {
        type: 'upload',
        fileType: 'pdf',
        fileName: 'progress-report.pdf',
        fileSize: 1024,
        description: 'HVAC begins Zone A duct installation',
      },
      consequences: [],
      triggeredEvents: [],
      metadata: {
        probability: 1.0,
        dependencies: ['mt-event-016'],
        skippable: false,
        interactive: false,
        emphasis: 'normal',
      },
      data: {
        progressType: 'start',
        zone: 'Zone A',
        workType: 'Main trunk and branch duct installation',
        crewSize: 4,
      },
    },
    {
      id: 'mt-event-019',
      urn: 'urn:ectropy:event:mt-event-019',
      type: 'progress',
      position: { week: 3, day: 3, hour: 16 },
      actor: 'contractor',
      persona: 'electrical-foreman-001',
      priority: 'normal',
      title: 'Electrical Progress Update - 70%',
      description: 'Electrical 70% complete in Zone A',
      voxelRefs: [],
      decisionRefs: [],
      payload: {
        type: 'progress',
        workCompleted: 'Electrical conduit and wire pull',
        percentComplete: 70,
        phase: 'rough_in',
        notes: 'Conduit complete, pulling wire',
      },
      consequences: [],
      triggeredEvents: [],
      metadata: {
        probability: 1.0,
        dependencies: ['mt-event-008'],
        skippable: true,
        interactive: false,
        emphasis: 'normal',
      },
      data: {
        progressPercent: 70,
        zone: 'Zone A',
        notes: 'Conduit complete, pulling wire',
      },
    },
    {
      id: 'mt-event-020',
      urn: 'urn:ectropy:event:mt-event-020',
      type: 'quality_check',
      position: { week: 3, day: 4, hour: 10 },
      actor: 'contractor',
      persona: 'mep-coordinator-001',
      priority: 'normal',
      title: 'MEP Progress Walkthrough',
      description: 'MEP coordinator performs progress walkthrough',
      voxelRefs: [],
      decisionRefs: [],
      payload: {
        type: 'quality_check',
        checkType: 'visual',
        criteria: ['Progress status', 'Coordination compliance'],
        inspector: 'mep-coordinator-001',
        result: 'passed',
        findings: ['All trades on schedule, coordination working well'],
      },
      consequences: [],
      triggeredEvents: [],
      metadata: {
        probability: 1.0,
        dependencies: ['mt-event-019'],
        skippable: false,
        interactive: false,
        emphasis: 'normal',
      },
      data: {
        checkType: 'progress_review',
        zone: 'Zone A',
        findings: 'All trades on schedule, coordination working well',
        punchItems: 0,
      },
    },
    {
      id: 'mt-event-021',
      urn: 'urn:ectropy:event:mt-event-021',
      type: 'progress',
      position: { week: 3, day: 5, hour: 16 },
      actor: 'contractor',
      persona: 'hvac-foreman-001',
      priority: 'normal',
      title: 'HVAC Progress Update - 50%',
      description: 'HVAC 50% complete in Zone A',
      voxelRefs: [],
      decisionRefs: [],
      payload: {
        type: 'progress',
        workCompleted: 'HVAC ductwork',
        percentComplete: 50,
        phase: 'rough_in',
        notes: 'Main trunk complete, branches in progress',
      },
      consequences: [],
      triggeredEvents: [],
      metadata: {
        probability: 1.0,
        dependencies: ['mt-event-018'],
        skippable: true,
        interactive: false,
        emphasis: 'normal',
      },
      data: {
        progressPercent: 50,
        zone: 'Zone A',
        notes: 'Main trunk complete, branches in progress',
      },
    },

    // Week 4: Inspection milestone
    {
      id: 'mt-event-022',
      urn: 'urn:ectropy:event:mt-event-022',
      type: 'progress',
      position: { week: 4, day: 1, hour: 16 },
      actor: 'contractor',
      persona: 'electrical-foreman-001',
      priority: 'normal',
      title: 'Electrical Zone A Complete',
      description: 'Electrical 100% complete in Zone A',
      voxelRefs: [],
      decisionRefs: [],
      payload: {
        type: 'progress',
        workCompleted: 'Electrical rough-in',
        percentComplete: 100,
        phase: 'rough_in',
        notes: 'All rough-in complete, devices ready for trim',
      },
      consequences: [],
      triggeredEvents: [],
      metadata: {
        probability: 1.0,
        dependencies: ['mt-event-019'],
        skippable: false,
        interactive: false,
        emphasis: 'normal',
      },
      data: {
        progressPercent: 100,
        zone: 'Zone A',
        notes: 'All rough-in complete, devices ready for trim',
      },
    },
    {
      id: 'mt-event-023',
      urn: 'urn:ectropy:event:mt-event-023',
      type: 'inspection',
      position: { week: 4, day: 2, hour: 9 },
      actor: 'regulatory',
      persona: 'mep-coordinator-001',
      priority: 'high',
      title: 'MEP Rough-in Inspection',
      description: 'Coordinated MEP rough-in inspection',
      voxelRefs: [],
      decisionRefs: [],
      payload: {
        type: 'inspection',
        inspectionType: 'ROUGH_IN',
        scheduledDate: { week: 4, day: 2, hour: 9 },
        inspector: 'City Building Inspector',
        requirements: [
          'Plumbing installation',
          'Electrical installation',
          'HVAC installation',
        ],
        result: 'passed',
      },
      consequences: [],
      triggeredEvents: ['mt-event-024'],
      metadata: {
        probability: 1.0,
        dependencies: ['mt-event-022'],
        skippable: false,
        interactive: true,
        emphasis: 'highlighted',
      },
      data: {
        inspectionType: 'rough_in',
        trades: ['plumbing', 'electrical', 'hvac'],
        inspector: 'City Building Inspector',
        zone: 'Zone A',
      },
    },
    {
      id: 'mt-event-024',
      urn: 'urn:ectropy:event:mt-event-024',
      type: 'approval',
      position: { week: 4, day: 2, hour: 14 },
      actor: 'regulatory',
      persona: 'mep-coordinator-001',
      priority: 'high',
      title: 'Inspection Passed',
      description: 'Inspection PASSED - all trades approved',
      voxelRefs: [],
      decisionRefs: [],
      payload: {
        type: 'approval',
        approvalType: 'inspection',
        approvedBy: 'regulatory',
        conditions: [],
      },
      consequences: [],
      triggeredEvents: [],
      metadata: {
        probability: 1.0,
        dependencies: ['mt-event-023'],
        skippable: false,
        interactive: false,
        emphasis: 'highlighted',
      },
      data: {
        approvalType: 'inspection',
        result: 'passed',
        notes: 'Clean inspection, no corrections required',
        permitUpdate: 'Rough-in approved, close-in authorized',
      },
    },

    // Week 5: Zone B work
    {
      id: 'mt-event-025',
      urn: 'urn:ectropy:event:mt-event-025',
      type: 'upload',
      position: { week: 4, day: 3, hour: 8 },
      actor: 'contractor',
      persona: 'plumbing-foreman-001',
      priority: 'normal',
      title: 'Plumbing Zone B Started',
      description: 'Plumbing mobilizes to Zone B',
      voxelRefs: [],
      decisionRefs: [],
      payload: {
        type: 'upload',
        fileType: 'pdf',
        fileName: 'progress-report.pdf',
        fileSize: 1024,
        description: 'Plumbing mobilizes to Zone B',
      },
      consequences: [],
      triggeredEvents: [],
      metadata: {
        probability: 1.0,
        dependencies: ['mt-event-024'],
        skippable: false,
        interactive: false,
        emphasis: 'normal',
      },
      data: {
        progressType: 'start',
        zone: 'Zone B',
        workType: 'Domestic water and drain rough-in',
        lessonApplied: 'Pre-coordinated routing with electrical',
      },
    },
    {
      id: 'mt-event-026',
      urn: 'urn:ectropy:event:mt-event-026',
      type: 'progress',
      position: { week: 5, day: 3, hour: 16 },
      actor: 'contractor',
      persona: 'hvac-foreman-001',
      priority: 'normal',
      title: 'HVAC Zone A Complete',
      description: 'HVAC 100% complete in Zone A',
      voxelRefs: [],
      decisionRefs: [],
      payload: {
        type: 'progress',
        workCompleted: 'HVAC ductwork',
        percentComplete: 100,
        phase: 'rough_in',
        notes: 'All ductwork installed and sealed',
      },
      consequences: [],
      triggeredEvents: [],
      metadata: {
        probability: 1.0,
        dependencies: ['mt-event-021'],
        skippable: false,
        interactive: false,
        emphasis: 'normal',
      },
      data: {
        progressPercent: 100,
        zone: 'Zone A',
        notes: 'All ductwork installed and sealed',
      },
    },
    {
      id: 'mt-event-027',
      urn: 'urn:ectropy:event:mt-event-027',
      type: 'progress',
      position: { week: 5, day: 5, hour: 16 },
      actor: 'contractor',
      persona: 'plumbing-foreman-001',
      priority: 'normal',
      title: 'Plumbing Zone B Progress - 75%',
      description: 'Plumbing 75% complete in Zone B',
      voxelRefs: [],
      decisionRefs: [],
      payload: {
        type: 'progress',
        workCompleted: 'Plumbing rough-in',
        percentComplete: 75,
        phase: 'rough_in',
        notes: 'Ahead of schedule due to improved coordination',
      },
      consequences: [],
      triggeredEvents: [],
      metadata: {
        probability: 1.0,
        dependencies: ['mt-event-025'],
        skippable: true,
        interactive: false,
        emphasis: 'normal',
      },
      data: {
        progressPercent: 75,
        zone: 'Zone B',
        notes: 'Ahead of schedule due to improved coordination',
      },
    },

    // Week 6: Completion
    {
      id: 'mt-event-028',
      urn: 'urn:ectropy:event:mt-event-028',
      type: 'progress',
      position: { week: 6, day: 2, hour: 16 },
      actor: 'contractor',
      persona: 'electrical-foreman-001',
      priority: 'normal',
      title: 'Electrical Zone B Complete',
      description: 'Electrical 100% complete in Zone B',
      voxelRefs: [],
      decisionRefs: [],
      payload: {
        type: 'progress',
        workCompleted: 'Electrical rough-in',
        percentComplete: 100,
        phase: 'rough_in',
        notes: 'Zero conflicts due to pre-coordination',
      },
      consequences: [],
      triggeredEvents: [],
      metadata: {
        probability: 1.0,
        dependencies: ['mt-event-027'],
        skippable: false,
        interactive: false,
        emphasis: 'normal',
      },
      data: {
        progressPercent: 100,
        zone: 'Zone B',
        notes: 'Zero conflicts due to pre-coordination',
      },
    },
    {
      id: 'mt-event-029',
      urn: 'urn:ectropy:event:mt-event-029',
      type: 'inspection',
      position: { week: 6, day: 4, hour: 9 },
      actor: 'regulatory',
      persona: 'mep-coordinator-001',
      priority: 'high',
      title: 'Zone B Inspection',
      description: 'Zone B coordinated inspection',
      voxelRefs: [],
      decisionRefs: [],
      payload: {
        type: 'inspection',
        inspectionType: 'ROUGH_IN',
        scheduledDate: { week: 6, day: 4, hour: 9 },
        inspector: 'City Building Inspector',
        requirements: [
          'Plumbing installation',
          'Electrical installation',
          'HVAC installation',
        ],
        result: 'passed',
      },
      consequences: [],
      triggeredEvents: ['mt-event-030'],
      metadata: {
        probability: 1.0,
        dependencies: ['mt-event-028'],
        skippable: false,
        interactive: true,
        emphasis: 'highlighted',
      },
      data: {
        inspectionType: 'rough_in',
        trades: ['plumbing', 'electrical', 'hvac'],
        zone: 'Zone B',
        result: 'passed',
      },
    },
    {
      id: 'mt-event-030',
      urn: 'urn:ectropy:event:mt-event-030',
      type: 'milestone',
      position: { week: 6, day: 5, hour: 16 },
      actor: 'contractor',
      persona: 'gc-multi-001',
      priority: 'high',
      title: 'MEP Phase Complete',
      description: 'All MEP rough-in complete - phase milestone achieved',
      voxelRefs: [],
      decisionRefs: [],
      payload: {
        type: 'milestone',
        milestoneName: 'MEP Rough-in Complete',
        phase: 'rough_in',
        percentComplete: 100,
        deliverables: [
          'All plumbing complete',
          'All electrical complete',
          'All HVAC complete',
          'All inspections passed',
        ],
      },
      consequences: [],
      triggeredEvents: [],
      metadata: {
        probability: 1.0,
        dependencies: ['mt-event-029'],
        skippable: false,
        interactive: false,
        emphasis: 'critical',
      },
      data: {
        milestoneType: 'phase_complete',
        summary: {
          totalConflicts: 1,
          conflictsResolved: 1,
          inspectionsPassed: 2,
          scheduleVariance: '-2 days (ahead)',
          costVariance: '+$550 (under budget allowance)',
        },
        nextPhase: 'Insulation and drywall',
      },
    },
  ];

  // ============================================================================
  // SCENARIO CONFIGURATION
  // ============================================================================

  return {
    id: 'multi-trade-coordination',
    name: 'Multi-Trade Coordination',
    description:
      'Complex MEP coordination scenario demonstrating conflict detection, ' +
      'resolution workflows, and synchronized multi-trade scheduling for a ' +
      'commercial office build-out.',
    version: '1.0.0',
    author: 'Ectropy Demo Team',

    buildingType: 'commercial-office' as BuildingType,
    duration: {
      weeks: 6,
      acceleratedMinutes: 30,
      defaultPlaybackSpeed: 10,
      description: 'MEP rough-in phase for 2-zone commercial office',
    },
    complexity: 'high',

    personas,
    milestones,
    timeline,

    voxelGeneratorOptions: {
      buildingProfile: 'office',
      zones: 2,
      floorsPerZone: 2,
      statusDistribution: {
        complete: 0.15,
        in_progress: 0.35,
        scheduled: 0.3,
        pending_decision: 0.1,
        blocked: 0.05,
        not_started: 0.05,
      },
    },

    presentationConfig: {
      recommendedDuration: '25-30 minutes',
      targetAudience: [
        'General Contractors',
        'MEP Coordinators',
        'Project Managers',
      ],
      keyDemoPoints: [
        'Real-time conflict detection saves costly rework',
        'Democratic resolution process maintains trade relationships',
        'Coordinated inspections reduce delays',
        'Proactive scheduling prevents conflicts',
      ],
      defaultPlaybackSpeed: 10,
    },
  };
}

// Export scenario with default demo project ID
export const multiTradeScenario = createMultiTradeScenario(
  'demo-project-multi-trade'
);
